services:
  atontask.webapi:
    image: atontask.webapi
    build:
      context: .
      dockerfile: AtonTask.WebApi/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: atontaskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: